name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        go:
          - '1.21'
        include:
        - go: '1.21'
          GO_SEMVER: '~1.21.0'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.GO_SEMVER }}
          check-latest: true

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build pzip
        working-directory: ./cmd/pzip
        env:
          CGO_ENABLED: 0
        run: |
          go build -v

      - name: Build punzip
        working-directory: ./cmd/punzip
        env:
          CGO_ENABLED: 0
        run: |
          go build -v


      - name: Run tests
        run: |
          go test -v -race ./...


  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: check
        env:
          TAG: ${{ steps.vars.outputs.version_tag }}
